### ISSUE TITLE
Result of `sample` changed between v2 and master

### ISSUE THREAD

**Issue by giordano** [PieterjanRobbe/GaussianRandomFields.jl#20]
I just noticed that the result of the following code changed between [`v2.0.0`](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/tree/v2.0.0):
```julia
julia> using GaussianRandomFields

julia> rnn = [0.9, 0.9, 0.9, 0.9];

julia> x = 1.0:2.0;

julia> y = 1.0:2.0;

julia> dim = 2
2

julia> cov = CovarianceFunction(dim, Matern(1.0, 1.0, σ = 1.0))
2d Matérn covariance function (λ=1.0, ν=1.0, σ=1.0, p=2.0)

julia> grf = GaussianRandomField(cov, CirculantEmbedding(), x, y, minpadding = 0)
Gaussian random field with 2d Matérn covariance function (λ=1.0, ν=1.0, σ=1.0, p=2.0) on a 2×2 structured grid, using a circulant embedding

julia> GaussianRandomFields.sample(grf, xi = rnn)
2×2 Array{Float64,2}:
 1.70787   0.381248
 0.381248  0.180234
```
and current [`master`](https://github.com/PieterjanRobbe/GaussianRandomFields.jl/tree/3c4122f4effd97314e05850776f96bdcf4694a6d):
```julia
julia> rnn = [0.9, 0.9, 0.9, 0.9];

julia> x = 1.0:2.0;

julia> y = 1.0:2.0;

julia> dim = 2
2

julia> cov = CovarianceFunction(dim, Matern(1.0, 1.0, σ = 1.0))
2d Matérn covariance function (λ=1.0, ν=1.0, σ=1.0, p=2.0)

julia> grf = GaussianRandomField(cov, CirculantEmbedding(), x, y, minpadding = 0)
Gaussian random field with 2d Matérn covariance function (λ=1.0, ν=1.0, σ=1.0, p=2.0) on a 2×2 structured grid, using a circulant embedding

julia> GaussianRandomFields.sample(grf, xi = rnn)
2×2 Array{Float64,2}:
 1.62387   0.511596
 0.511596  0.282107
```
Is there a reason why this happened?

**Comment by PieterjanRobbe** [comment]
Yes, someone recently pointed out irl that it is much more common to define the Matérn kernel as

C(\rho) = \sigma \frac{2^{1-\nu}}{\Gamma(\nu)}\left(\frac{\rho}{\lambda}\right)^\nu K_\nu\left(\frac{\rho}{\lambda}\right),

instead of the previous definition

C(\rho) = \sigma \frac{2^{1-\nu}}{\Gamma(\nu)}\left(\sqrt{2 \nu} \frac{\rho}{\lambda}\right)^\nu K_\nu\left(\sqrt{2 \nu} \frac{\rho}{\lambda}\right).

(including a \sqrt{2 \nu} in the argument), see 777d0a1. Which version of the two do you prefer?

**Comment by giordano** [comment]
I don't have a strict preference, but I'd like to have stable numbers to test against :grin:

**Comment by giordano** [comment]
But ok, I wanted to double check why that changed.  I think I'll just move on to use v2.1 as soon as it is available.  Thanks!
