### ISSUE TITLE
Matern covariance kernel equation incorrect

### ISSUE THREAD

**Issue by gerrygralton** [PieterjanRobbe/GaussianRandomFields.jl#39]
Hi,
The Matern kernel equation has been giving me some funny results and the equation doesn't match [the one on wikipedia](https://en.wikipedia.org/wiki/Mat%C3%A9rn_covariance_function). I'll submit a pull request with a fix shortly.
Cheers,
Gerry

**Comment by PieterjanRobbe** [comment]
Hi @gerrygralton, thanks for pointing that out! I think the story of the Matérn covariance function is a bit more convoluted than what is sketched in [the Wikipedia article](https://en.wikipedia.org/wiki/Mat%C3%A9rn_covariance_function). I believe there are in fact multiple equivalent representations of the same covariance structure. The three parameterisations I can think of right now are:
- **The Matérn parameterisation** (originally proposed in Matérn's PhD thesis, see [1])
`C1(r) = 2^(1 - nu) / Gamma(nu) * (sqrt(2*nu) * r)^nu * besselk(nu, sqrt(2*nu) * r)` 
- **The Whittle parameterisation** (as the solution of a fractional SDE, see [2])
`C2(r) = 2^(1 - nu) / Gamma(nu) * r^nu * besselk(nu, r)` 
- **The Handcock-Wallis** parameterisation (while analyzing historical temperature data in the northern US in [3])
`C3(r) = 2^(1 - nu) / Gamma(nu) * (2 * sqrt(nu) * r)^nu * besselk(nu, 2 * sqrt(nu) * r)`

I don't recall all the details, but there are specific parameterisations that make more sense than others, depending on which (mathematical) properties you are after. I think I changed the implementation from the Matérn parameterisation to the Whittle parametrisation a while back because it made more sense in my application at that time.

I'd support the proposed change in principle, but I'm a bit worried that this may break other people's code (@giordano ?).

If you need the Matérn parameterisation, you can just [implement a custom covariance function](https://pieterjanrobbe.github.io/GaussianRandomFields.jl/stable/tutorial/#Defining-Custom-Covariance-Functions-1).

An even better approach would be to link `GaussianRandomFields.jl` to [`KernelFunctions.jl`](KernelFunctions.jl). I believe they have all that stuff sorted out there (see #32).

[1] Matérn, B. *Spatial Variation – Stochastic Models and their Application to Some Problems in Forest Surveys and other Sampling Investigations.* PhD thesis, Statens Skogsforskningsinstitut, Stockholm, Sweden, 1960. 
[2] Handcock, M. S., and Wallis, J. R. *An Approach to Statistical Spatial-Temporal Modeling of Meteorological Fields.* Journal of the American Statistical Association 89, 426 (1994), 368–378. 
[3] Whittle, P. *On Stationary Processes* in the Plane. Biometrika 41 (1954), 434–449.

**Comment by giordano** [comment]
> but I'm a bit worried that this may break other people's code (@giordano ?).

I can confirm it would :sweat_smile:

**Comment by gerrygralton** [comment]
The property that I was after was a consistent length scale with a Gaussian kernel. I've fixed my problem with a custom covariance kernel but just thought that I would point this out in case it was a real problem. 
I'm not fussed either way. It's definitely easier and less disruptive to maintain the status quo and forget I said anything!
